### PR TITLE
Migration to SQL

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
This PR will do a couple of things:
- Migrate the project to use SQL (PostgreSQL, although it's interchangeable with stuff like MariaDB or MySQL)
- Migrate to using PnPM for disk efficiency and faster package download/installation

Essentially, migrating to using SQL over MongoDB will be helpful in the long run, as using a SQL database provides a lot more stability and scalability (especially when using local + master nodes) that a document database won't have.

This is currently a WIP draft! Please don't merge yet!

### CODE REVIEW

**Comment by NathanX-S** [comment]
I don't believe that SQL will be superior to MongoDB in this context, especially given the sheer amount/variety/"structures" of data.

**Comment by RedstoneWizard08** [comment]
Possibly, but when you think about the number of documents that will be there when the project is open to people adding data, it can get ***really*** slow and inefficient. I made this exact same mistake (using MongoDB for a lot of data) a while ago, and I think that it would be better to move this over to SQL early instead of causing that problem later on. Also, with tools like Prisma (which I've used here), it can be really easy to work with a SQL database.

**Comment by megascatterbomb** [comment]
I speak from experience on this:

MongoDB is infinitely easier to manage than SQL. Gonna stay that way.

**Comment by Oman395** [comment]
> Possibly, but when you think about the number of documents that will be there when the project is open to people adding data, it can get _**really**_ slow and inefficient. I made this exact same mistake (using MongoDB for a lot of data) a while ago, and I think that it would be better to move this over to SQL early instead of causing that problem later on. Also, with tools like Prisma (which I've used here), it can be really easy to work with a SQL database.

Realistically the performance should be fine-- actual reports with large amounts of data will happen much less often than the standard requests for user statuses. Additionally, caching on both sides should mean that a majority of requests don't even need to read from the DB-- several clients would be asking about the status of the same users, so in theory caching should limit DB calls significantly. Also, IIRC from the video the old system was mongo, so the migration of data from that should be smoother, as well as all the developers being more familiar with it.

**Comment by RedstoneWizard08** [comment]
Fair. I might work on some sort of management UI for this then. I think that might be a good step.

**Comment by RedstoneWizard08** [comment]
@megascatterbomb What MongoDB library are you planning to use? Either I'm blind or I couldn't find that.

**Comment by megascatterbomb** [comment]
> @megascatterbomb What MongoDB library are you planning to use? Either I'm blind or I couldn't find that.

I used mongoose on the OG database, intend on using the same for this.

**Comment by RedstoneWizard08** [comment]
Okay.

**Comment by RedstoneWizard08** [comment]
Is the code for the original one available? I just want to do this as accurately as possible. (Sorry for asking so many questions :p )

**Pull request closed without merging**
